require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-elastic-log.gemspec
    - test/**/*.rb

Naming/MethodParameterName:
  Exclude:
    - lib/fluent/plugin/out_elastic_audit_log_metric.rb
