require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-elastic-log.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Exclude:
    - test/helper.rb

Naming/MethodParameterName:
  Exclude:
    - lib/fluent/plugin/out_elastic_audit_log_metric.rb
